# core/explainer_langchain.py

def explain_log(log_text):
    """
    Simple offline explainer for critical log messages.
    Replace this logic with LangChain-GPT call if online.
    """
    if "file not found" in log_text.lower():
        return {
            "explanation": "File missing error usually occurs when input file path is invalid or file is missing.",
            "causes": ["Incorrect file path", "File not generated by upstream", "File deleted accidentally"],
            "suggestions": ["Verify path", "Check upstream job", "Regenerate missing file"]
        }
    elif "connection timeout" in log_text.lower():
        return {
            "explanation": "Connection timeout occurs when network connectivity fails or server is down.",
            "causes": ["Network failure", "Server overload", "Misconfigured port settings"],
            "suggestions": ["Check network", "Increase timeout limit", "Verify server availability"]
        }
    else:
        return {
            "explanation": "Unknown log type. Please analyze manually.",
            "causes": ["Unknown issue"],
            "suggestions": ["Use manual debugging or consult logs team"]
        }

# Sample test
if __name__ == "__main__":
    log = "ERROR FileProcessor - file not found: /input/data.csv"
    result = explain_log(log)
    print(result)
